### ISSUE TITLE
[BUG] Tables are collapsed

### ISSUE THREAD

**Issue by devgeni** [curvenote/prosemirror-docx#12]
Rendering document with tables. But they are all collapsed.
I tried fixing the source code and it didn't help:
```ts
const tableCellOpts: Mutable<ITableCellOptions> = {
  children: this.children,
  width: { size: Math.floor(100 / rowContent.childCount), type: WidthType.PERCENTAGE },
};
```
Example, how it looks:
<img width="703" alt="image" src="https://user-images.githubusercontent.com/26095528/158836054-cbaafb85-7ee1-43f2-8821-018c68ecc8f9.png">

**Comment by rowanc1** [comment]
Would this be related to this: https://github.com/dolanmiu/docx/issues/1457

**Comment by devgeni** [comment]
Yeah, exactly this, thanks!
