### ISSUE TITLE
No more compatible with docx since v8.5.0

### ISSUE THREAD

**Issue by jlchereau** [curvenote/prosemirror-docx#21]
This now fails (used to work fine with versions 8.4.0 and prior):

```
import { defaultDocxSerializer } from 'prosemirror-docx';
import { Packer } from 'docx';
import { saveAs } from 'file-saver';

const input = proseMirrorElement.current.value();
const wordDocument = defaultDocxSerializer.serialize(input, {});
const blob = await Packer.toBlob(wordDocument);
saveAs(blob, 'whatever.docx');

```

Issue seems to be related to missing FontTable after https://github.com/dolanmiu/docx/pull/2174

**Comment by dan-cooke** [comment]
Checkout our fork https://github.com/templi-ai/prosemirror-docx

**Comment by jlchereau** [comment]
Fixed with https://github.com/curvenote/prosemirror-docx/releases/tag/v0.2.0. Thx.
