### ISSUE TITLE
This repo is unmaintained

### ISSUE THREAD

**Issue by dan-cooke** [curvenote/prosemirror-docx#24]
Hey all!

If you stumble across this super useful library - we have recently forked it over at https://github.com/templi-ai/prosemirror-docx

Thanks to the authors - its been invaluable in our app. 

We will be mantaining this fork for the forseeable and have already updated various dependencies and added features.

We also plan to release `extension-export-to-word` for TipTap editor which will be based on this plugin.

PS. if the authors return we are happy to merge our Fork into this repo

**Comment by rowanc1** [comment]
Thank you @dan-cooke, if you would like to be a maintainer here we could use the help. We are focused on export workflows through myst markdown (https://mystmd.org) at the moment.

**Comment by dan-cooke** [comment]
@rowanc1  absolutely. happy to help!

I will make a PR for my fork.

However I don't see a worfklow to publish the package anywhere, are you just doing this manually? 

That would be a good first step - if you could add NPM_TOKEN that has permission to publish https://www.npmjs.com/package/prosemirror-docx to the github actions and make me mantainer - i can setup the auto publish worfklows

**Comment by rowanc1** [comment]
Yes, I likely did it manually. I will add the token, you have been added as a maintainer! :)

**Comment by rowanc1** [comment]
NPM_TOKEN has been added (granular access token):

![image](https://github.com/curvenote/prosemirror-docx/assets/913249/9755ca5a-4bba-4a3d-ae7f-f94fa371ef3d)

**Comment by dan-cooke** [comment]
@rowanc1 perfect - I’ll get this all published in the next few days
