### ISSUE TITLE
superscript is not handled correctly

### ISSUE THREAD

**Issue by kozborn** [curvenote/prosemirror-docx#7]
After exporting to word I noticed that `superscript` are treated like `subscript` and I guess it is because of this line

https://github.com/curvenote/prosemirror-docx/blob/6975bd1c6edc5a80d07a9d6953c5a5818bd03ab7/src/schema.ts#L103

**Comment by rowanc1** [comment]
Quite right!

Fixed in 782d7d6267d2ed46977f873613f7adc3a427efa8
